# Generated by Django 5.0.1 on 2024-07-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='isim',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='tarih',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='yorum',
        ),
    ]
